[package]
name = "rei-treicem"
version = "0.1.0"
authors = ["Alice Micheloni <alicemicheloni@tutanota.com>"]
edition = "2018"

[dependencies]
rand = "0.8.0"
rayon = "1.5.0"
image = "0.21.0"
halton = "0.2.1"
